# Generated by Django 5.2.13 on 2026-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='advertisement_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='is_advertisement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='ads_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='ads_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
